### ISSUE TITLE
Error link template notion

### ISSUE THREAD

**Issue by bekat** [mendesaltaren/product-design-handbook#1]
There is an error in the section of notion:
https://designhandbook.mendesaltaren.com/tools/notion

<img width="783" alt="screen shot 2018-10-02 at 18 19 24" src="https://user-images.githubusercontent.com/14014155/46363241-c2b4cb80-c672-11e8-99cf-872d17153204.png">

Gives a 404 error when entering the page

Thanks!

**Comment by guerrero** [comment]
Fixed! Thanks David ;)
