### ISSUE TITLE
Documenting the tools used for generating the diagrams?

### ISSUE THREAD

**Issue by mmoya** [mendesaltaren/product-design-handbook#11]
Hello
I'd be possible to know (or add to README.txt) what tool did you use to generate the diagram in § 2.3.22 (Analítica cuantitativa) ?

Thanks

**Comment by guerrero** [comment]
Sorry for the late response @mmoya and thanks for your interest.

That diagram was created using Figma. [Figma](https://www.figma.com) is the way to go in (almost) every design at mendesaltaren. In the past, we used [Miro](https://miro.com/), [Whimsical](https://whimsical.com/) and even [diagrams.net](http://www.diagrams.net/)  but now that Figma has released FigJam we prefer to use one tool only.

Said that, this is an old version of our handbook. Here's a link to the new one in case you want to check it out: https://www.mendesaltaren.com/handbook
