### ISSUE TITLE
La URL de la descripción del repositorio es incorrecta

### ISSUE THREAD

**Issue by Angelmmiguel** [mendesaltaren/product-design-handbook#4]
La URL apunta a https://mendesaltaren.gitbook.io/design-techniques/ cuando debería apuntar a https://mendesaltaren.gitbook.io/product-design-handbook/.

![screenshot 2018-10-03 at 09 30 30](https://user-images.githubusercontent.com/4056725/46396198-fe8d7680-c6ee-11e8-9a2a-cf3e1fb39d19.png)

PS: Gracias por el libro! Una pasada :)

**Comment by guerrero** [comment]
Ups! Bien visto y mil gracias por reportarlo y por la acogida ;)
